### ISSUE TITLE
Regression in v1.5.2

### ISSUE THREAD

**Issue by SchnWalter** [23andMe/Yamale#22]
Hello,
It looks like there was a regression in v1.5.2. Could you please look over it.
```
# Clean
$ pip uninstall yamale

# Test is OK with Yamale v1.5.0
$ pip install yamale==1.5.0
$ python regression_test.py
DONE!


# Test fails with Yamale v1.5.2
$ pip install --upgrade yamale==1.5.2
$ python regression_test.py
Traceback (most recent call last):
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/util.py", line 65, in get_value
    return reduce(getitem, path, dic)[last_key]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "regression_test.py", line 12, in <module>
    yamale.validate(schema, data)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/yamale.py", line 30, in validate
    schema.validate(d)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 44, in validate
    errors += self._validate(validator, data, key=key, includes=self.includes)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 76, in _validate
    return self._validate_item(validator, data_item, position, includes)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 100, in _validate_item
    includes, position)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 122, in _validate_map_list
    err = self._validate(v, data, key, pos, includes)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 76, in _validate
    return self._validate_item(validator, data_item, position, includes)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 96, in _validate_item
    includes, position)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 142, in _validate_include
    errors += include_schema._validate(validator, data, includes=includes, key=key, position=pos)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/schema.py", line 68, in _validate
    data_item = util.get_value(data, key)
  File "/workspace/android/mission-impossible-android/.venv/lib/python3.4/site-packages/yamale/schema/util.py", line 67, in get_value
    return reduce(getitem, path, dic)[int(last_key)]
ValueError: invalid literal for int() with base 10: 'id'
```

This is the schema that is no longer working.
```
apps: >
  list(
    str(),
    include('app_fdroid_latest'),
  )

---

app_fdroid_latest:
  id: str()
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)
```
I have uploaded the tests here: https://www.mission.li/regression_test.tar.gz

Thank you,
Walter S.

**Comment by blopker** [comment]
Hey, thank you for the report and the tests! I added your yaml files to our test suite. 1.5.3 is now on PyPI.
